# Generated by Django 4.2.5 on 2023-10-04 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestorTareas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GestorTareas.task')),
            ],
        ),
        migrations.DeleteModel(
            name='TaskList',
        ),
    ]
